version: '3.3'

services:
  ddcc:
    container_name: ddcc-transactions-mediator
    image: censcl/ops-ddcc-transactions-mediator-lacpass-ips:latest
    networks:
      - ddcc-net
    environment:
      FHIR_SERVER: '${FHIR_SERVER:?err}'
      MATCHBOX_SERVER: 'http://resource-generation-service:8080/fhir/'
      PRIVATE_KEY_FILE: '/app/cert-data/DSC01privkey.key'
      PUBLIC_KEY_FILE: '/app/cert-data/DSCcert.pem'
      COUNTRY_CODE: 'XCL'
    volumes:
      - ./../cert-data:/app/cert-data
    ports:
      - "4321:4321"
    depends_on:
      - resource-generation-service

  resource-generation-service:
    container_name: resource-generation-service
    image: censcl/ops-ddcc-resource-generation-service:v2.0
    networks:
      - ddcc-net
    ports:
        - "8023:8080"

networks:
  ddcc-net:
    external: false
    name: ddcc-net